#!/bin/bash

source $(dirname $0)/../common.sh
monitor_id="HDMI-0"

load_machine_defaults
set_machine_monitors $monitor_id
set_i3_gaps 10 2 2
set_polybar_mode solo
set_polybar_options 32 12 9
set_random_background $monitor_id
postswitch 110 false
