---
window:
  padding:
    x: 2
    y: 2
  dynamic_padding: true

font:
  normal:
    family: FuraMono Nerd Font
    style: Regular

  bold:
    family: FuraMono Nerd Font
    style: Bold

  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  bold_italic:
    family: SauceCodePro Nerd Font
    style: Bold Italic

  size: 10.0

draw_bold_text_with_bright_colors: true

key_bindings:
  - { key: H, mods: Control|Shift, chars: "\x1b[72;5u" }
  - { key: J, mods: Control|Shift, chars: "\x1b[74;5u" }
  - { key: K, mods: Control|Shift, chars: "\x1b[75;5u" }
  - { key: L, mods: Control|Shift, chars: "\x1b[76;5u" }
