#!/bin/bash
#
# LCD "15.6 @ 1920x1080
# Monitor DPI: 141
#

source $(dirname $0)/../common.sh
monitor_id="eDP-1"

echo "---"
load_machine_defaults
set_machine_monitors eDP-1
set_i3_gaps 3 0 1
set_polybar_mode solo
set_polybar_options 36 12 9
set_random_background $monitor_id
postswitch 144 false
